name: github pages

on:
  push:
    branches:
      - master
      - feature/buildstorybook

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: install base packages
        run: yarn

      - name: build base packages
        run: yarn build

      - name: build storybook site
        run: yarn build:storybook

      - name: Deploy
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./packages/react/storybook-static
          SCRIPT_MODE: "true"
        run: |
          wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.5.0/entrypoint.sh
          bash ./entrypoint.sh
          # with:
          # keepFiles: true
